### ISSUE TITLE
How to use API?

### ISSUE THREAD

**Issue by pyroteck** [louismeunier/mechgroupbuys-api-wrapper#1]
Hi, I'm building a small project that would ideally use this API, how do I use this? Every time I call the API I get `{ error: 'invalid route' }` or `{"error":{"invalid_status":":status is not a valid status, must be one [\"live\",\"upcoming\",\"ic\",\"ended\"]"}}`

**Comment by louismeunier** [comment]
What exact request are you making that is giving you that error?

**Comment by louismeunier** [comment]
I've looked into the potential issue a little more, I believe the error was caused by using an old version of axios. Try accessing the API (eg: http://mechgroupbuyswrapper.herokuapp.com/keyboards?status=live) now and let me know if the error persists.

**Comment by pyroteck** [comment]
perfect, I'm getting the JSON now, thanks!
